gst-devtools/fault_injection: fix build failure on musl due to different connect signature
Specifically, this occurs when using clang and musl C library (instead of glibc):

| ../gst-devtools-1.24.12/validate/plugins/fault_injection/socket_interposer.c:103:1: error: conflicting types for 'connect'
|   103 | connect (int socket, const struct sockaddr_in *addrin, socklen_t address_len)
|       | ^
| /srv/storage/alex/yocto/build-clang/tmp/work/core2-64-poky-linux-musl/gst-devtools/1.24.12/recipe-sysroot/usr/include/sys/socket.h:386:5: note: previous declaration is here
|   386 | int connect (int, const struct sockaddr *, socklen_t);
|       |     ^